package com.qc.model;

// Generated 2016-10-18 11:21:58 by Hibernate Tools 4.0.0

import java.io.File;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.framework.UploadHelper;
import com.framework.UploadType;

/**
 * Carousel generated by hbm2java
 */
@Entity
@Table(name = "carousel", catalog = "qcplus")
public class Carousel implements java.io.Serializable {

	private int id;
	private String descInfo;
	private String imagePath;
	private Date createDate;
	private Integer orderNo;
	private String url;
	//
	private String httpPath;

	
	

	
	@Transient
	public String getHttpPath() {
		return UploadType.HTTP_DIRTECTORY_PREIX+File.separator+imagePath;
	}

	public void setHttpPath(String httpPath) {
		this.httpPath = httpPath;
	}
	@Column(name="url")
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}

	public Carousel() {
	}

	public Carousel(int id, Date createDate) {
		this.id = id;
		this.createDate = createDate;
	}

	public Carousel(int id, String descInfo, String imagePath, Date createDate,
			Integer orderNo) {
		this.id = id;
		this.descInfo = descInfo;
		this.imagePath = imagePath;
		this.createDate = createDate;
		this.orderNo = orderNo;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "descInfo", length = 100)
	public String getDescInfo() {
		return this.descInfo;
	}

	public void setDescInfo(String descInfo) {
		this.descInfo = descInfo;
	}

	@Column(name = "imagePath", length = 100)
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "orderNo")
	public Integer getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(Integer orderNo) {
		this.orderNo = orderNo;
	}

}
