package com.qc.model;

// Generated 2016-10-18 11:21:58 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Formula;

/**
 * Commentinfo generated by hbm2java
 */
@Entity
@Table(name = "commentinfo", catalog = "qcplus")
public class Commentinfo implements java.io.Serializable {

	/** 
	* @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
	*/ 
	private static final long serialVersionUID = -3975492777250723252L;
	private int id;
	private Integer orderId;
	private Integer userId;
	private String content;
	private Date descDate;
	private String score;

	@Column(name="score")
	public String getScore() {
		return score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	//自定义
	private String orderCode;
	private String loginname;
	@Formula("( select o.orderCode from orderdesc o where o.id = orderId )")
	public String getOrderCode() {
		return orderCode;
	}

	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}
	@Formula("(select u.loginname from user_login u where u.id=userId)")
	public String getLoginname() {
		return loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public Commentinfo() {
	}

	public Commentinfo(int id) {
		this.id = id;
	}

	public Commentinfo(int id, Integer orderId, Integer userId, String content,
			Date descDate,String score) {
		this.id = id;
		this.orderId = orderId;
		this.userId = userId;
		this.content = content;
		this.descDate = descDate;
		this.score = score;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "orderId")
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "userId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "content", length = 200)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "descDate", length = 10)
	public Date getDescDate() {
		return this.descDate;
	}

	public void setDescDate(Date descDate) {
		this.descDate = descDate;
	}

}
