package com.qc.model;

// Generated 2016-10-19 15:02:39 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hot generated by hbm2java
 */
@Entity
@Table(name = "hot", catalog = "qcplus")
public class Hot implements java.io.Serializable {

	private Integer id;
	private String title;
	private String contentDesc;
	private Date createDate;
	private Integer orderNo;

	public Hot() {
	}

	public Hot(Date createDate) {
		this.createDate = createDate;
	}

	public Hot(String title, String contentDesc, Date createDate,
			Integer orderNo) {
		this.title = title;
		this.contentDesc = contentDesc;
		this.createDate = createDate;
		this.orderNo = orderNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "ContentDesc", length = 65535)
	public String getContentDesc() {
		return this.contentDesc;
	}

	public void setContentDesc(String contentDesc) {
		this.contentDesc = contentDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "orderNo")
	public Integer getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(Integer orderNo) {
		this.orderNo = orderNo;
	}

}
