package com.qc.model;

// Generated 2016-10-18 11:21:58 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Formula;

/**
 * Messagecenter generated by hbm2java
 */
@Entity
@Table(name = "messagecenter", catalog = "qcplus")
public class Messagecenter implements java.io.Serializable {

	private int id;
	private Integer fromUser;
	private Integer toUser;
	private String content;
	private Integer infoType;
	private Integer status;
	//自定义
	private String fromUserName;
	private String toUserName;
	
	@Formula("(select u.loginname from user_login u where u.id=fromUser)")
	public String getFromUserName() {
		return fromUserName;
	}

	public void setFromUserName(String fromUserName) {
		this.fromUserName = fromUserName;
	}
	@Formula("(select u.loginname from user_login u where u.id=toUser)")
	public String getToUserName() {
		return toUserName;
	}

	public void setToUserName(String toUserName) {
		this.toUserName = toUserName;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	private Date sendTime;

	public Messagecenter() {
	}

	public Messagecenter(int id, Date sendTime) {
		this.id = id;
		this.sendTime = sendTime;
	}

	public Messagecenter(int id, Integer fromUser, Integer toUser,
			String content, Integer status,Integer infoType, Date sendTime) {
		this.id = id;
		this.fromUser = fromUser;
		this.toUser = toUser;
		this.content = content;
		this.status = status;
		this.infoType = infoType;
		this.sendTime = sendTime;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "fromUser")
	public Integer getFromUser() {
		return this.fromUser;
	}

	public void setFromUser(Integer fromUser) {
		this.fromUser = fromUser;
	}

	@Column(name = "toUser")
	public Integer getToUser() {
		return this.toUser;
	}

	public void setToUser(Integer toUser) {
		this.toUser = toUser;
	}

	@Column(name = "content", length = 500)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "infoType")
	public Integer getInfoType() {
		return this.infoType;
	}

	public void setInfoType(Integer infoType) {
		this.infoType = infoType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sendTime", nullable = false, length = 19)
	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

}
