package com.qc.model;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Formula;


/**
 * Moneychange generated by hbm2java
 */
@Entity
@Table(name = "moneychange", catalog = "qcplus")
public class Moneychange implements java.io.Serializable {

	private Integer id;
	private UserLogin userLogin;
	private Orderdesc orderdesc;
	private int value;
	private Date createDate;
	private Date changeDate;
	private Integer type;
	private Integer status;
	private Integer isdelete;
	
	private String statusName;
	private String typeName;
	
	@Formula("(select c.name from configuration c where c.catalog='changetype' and c.code=type)")
	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Moneychange() {
	}

	@Formula("(select c.name from configuration c where c.catalog='changestatus' and c.code=status)")
	public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	public Moneychange(UserLogin userLogin, int value, Date changeDate) {
		this.userLogin = userLogin;
		this.value = value;
		this.changeDate = changeDate;
	}

	public Moneychange(UserLogin userLogin, Orderdesc orderdesc, int value,
			Date createDate, Date changeDate, Integer type, Integer status,
			Integer isdelete) {
		this.userLogin = userLogin;
		this.orderdesc = orderdesc;
		this.value = value;
		this.createDate = createDate;
		this.changeDate = changeDate;
		this.type = type;
		this.status = status;
		this.isdelete = isdelete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public UserLogin getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(UserLogin userLogin) {
		this.userLogin = userLogin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orderId")
	public Orderdesc getOrderdesc() {
		return this.orderdesc;
	}

	public void setOrderdesc(Orderdesc orderdesc) {
		this.orderdesc = orderdesc;
	}

	@Column(name = "value", nullable = false)
	public int getValue() {
		return this.value;
	}

	public void setValue(int value) {
		this.value = value;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "changeDate", nullable = false, length = 19)
	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "isdelete")
	public Integer getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

}
