package com.qc.model;


import java.io.File;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import com.framework.UploadType;

/**
 * MoneychangeDesc generated by hbm2java
 */
@Entity
@Table(name = "moneychange_desc", catalog = "qcplus")
public class MoneychangeDesc implements java.io.Serializable {

	private Integer id;
	private int moneychangeid;
	private String attachfile;
	private String httpPath;
	@Transient
	public String getHttpPath() {
		return UploadType.HTTP_DIRTECTORY_PREIX+File.separator+attachfile;
	}

	public void setHttpPath(String httpPath) {
		this.httpPath = httpPath;
	}
	private String descrition;

	public MoneychangeDesc() {
	}

	public MoneychangeDesc(int moneychangeid) {
		this.moneychangeid = moneychangeid;
	}

	public MoneychangeDesc(int moneychangeid, String attachfile, String descrition) {
		this.moneychangeid = moneychangeid;
		this.attachfile = attachfile;
		this.descrition = descrition;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "moneychangeid", nullable = false)
	public int getMoneychangeid() {
		return this.moneychangeid;
	}

	public void setMoneychangeid(int moneychangeid) {
		this.moneychangeid = moneychangeid;
	}

	@Column(name = "attachfile")
	public String getAttachfile() {
		return this.attachfile;
	}

	public void setAttachfile(String attachfile) {
		this.attachfile = attachfile;
	}

	@Column(name = "descrition", length = 1000)
	public String getDescrition() {
		return this.descrition;
	}

	public void setDescrition(String descrition) {
		this.descrition = descrition;
	}

}
