package com.qc.model;

// Generated 2016-10-18 11:21:58 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.Formula;

import com.framework.Constants;

/**
 * Orderdesc generated by hbm2java
 */
@Entity
@Table(name = "orderdesc", catalog = "qcplus")
public class Orderdesc implements java.io.Serializable {
	private String serviceTypeName;
	private String receveIdName;
	private String rececompName;
	private String senderIdName;
	private String productTypeName;
	private String serviceProviderTypeName;
	private String orderstatusName;
	@Formula("(select t.name from dicservicetype t where t.id = serviceType)")
	public String getServiceTypeName() {
		return serviceTypeName;
	}

	public void setServiceTypeName(String serviceTypeName) {
		this.serviceTypeName = serviceTypeName;
	}
	
	@Formula("(select t.name from receiveorder t where t.id = receiveId and serviceProviderType=2)")
	public String getReceveIdName() {
		return receveIdName;
	}

	public void setReceveIdName(String receveIdName) {
		this.receveIdName = receveIdName;
	}
	
	
	@Formula("(select t.name from sendorder t where t.id = senderId)")
	public String getSenderIdName() {
		return senderIdName;
	}

	public void setSenderIdName(String senderIdName) {
		this.senderIdName = senderIdName;
	}
	@Formula("(select t.name from dicproducttype t where t.id = productType)")
	public String getProductTypeName() {
		return productTypeName;
	}

	public void setProductTypeName(String productTypeName) {
		this.productTypeName = productTypeName;
	}
	@Transient
	public String getServiceProviderTypeName() {
		if(1==this.serviceProviderType){
			return Constants.ORDER_SERVICEPROVIDERTYPE_1;
		}else if(2==this.serviceProviderType){
			return Constants.ORDER_SERVICEPROVIDERTYPE_2;
		}
		return null;
	}

	public void setServiceProviderTypeName(String serviceProviderTypeName) {
		this.serviceProviderTypeName = serviceProviderTypeName;
	}
	
	@Formula("(select t.name from receiveordercompany t where t.id = receiveId and serviceProviderType=1	)")
	public String getRececompName() {
		return rececompName;
	}

	public void setRececompName(String rececompName) {
		this.rececompName = rececompName;
	}
	
	@Formula("(select t.name from dicorderstatus t where t.id = status)")
	public String getOrderstatusName() {
		return orderstatusName;
	}

	public void setOrderstatusName(String orderstatusName) {
		this.orderstatusName = orderstatusName;
	}

	private int id;
	private String orderCode;
	private Integer serviceType;
	private Integer receiveId;
	private Integer senderId;
	private Date validateDate;
	private String supplyAddr;
	private Integer suppyCity;
	private String suppyAddrLatitude;
	private Integer productType;
	private Integer goodsCity;
	private String goodsAddr;
	private String goodsAddrLatitude;
	private Integer serviceProviderType;
	private String suppyContact;
	private String suppyTelephone;
	private String productDatum;
	private Integer status;
	private String remarks;
	private Date createDate;

	public Orderdesc() {
	}

	public Orderdesc(int id) {
		this.id = id;
	}

	public Orderdesc(int id, String orderCode, Integer serviceType,
			Integer receiveId, Integer senderId, Date validateDate,
			String supplyAddr, Integer suppyCity, String suppyAddrLatitude,
			Integer productType, Integer goodsCity, String goodsAddr,
			String goodsAddrLatitude, Integer serviceProviderType,
			String suppyContact, String suppyTelephone, String productDatum,
			Integer status, String remarks, Date createDate) {
		this.id = id;
		this.orderCode = orderCode;
		this.serviceType = serviceType;
		this.receiveId = receiveId;
		this.senderId = senderId;
		this.validateDate = validateDate;
		this.supplyAddr = supplyAddr;
		this.suppyCity = suppyCity;
		this.suppyAddrLatitude = suppyAddrLatitude;
		this.productType = productType;
		this.goodsCity = goodsCity;
		this.goodsAddr = goodsAddr;
		this.goodsAddrLatitude = goodsAddrLatitude;
		this.serviceProviderType = serviceProviderType;
		this.suppyContact = suppyContact;
		this.suppyTelephone = suppyTelephone;
		this.productDatum = productDatum;
		this.status = status;
		this.remarks = remarks;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "orderCode", length = 50)
	public String getOrderCode() {
		return this.orderCode;
	}

	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}

	@Column(name = "serviceType")
	public Integer getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(Integer serviceType) {
		this.serviceType = serviceType;
	}

	@Column(name = "receiveId")
	public Integer getReceiveId() {
		return this.receiveId;
	}

	public void setReceiveId(Integer receiveId) {
		this.receiveId = receiveId;
	}

	@Column(name = "senderId")
	public Integer getSenderId() {
		return this.senderId;
	}

	public void setSenderId(Integer senderId) {
		this.senderId = senderId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "validateDate", length = 10)
	public Date getValidateDate() {
		return this.validateDate;
	}

	public void setValidateDate(Date validateDate) {
		this.validateDate = validateDate;
	}

	@Column(name = "supplyAddr", length = 100)
	public String getSupplyAddr() {
		return this.supplyAddr;
	}

	public void setSupplyAddr(String supplyAddr) {
		this.supplyAddr = supplyAddr;
	}

	@Column(name = "suppyCity")
	public Integer getSuppyCity() {
		return this.suppyCity;
	}

	public void setSuppyCity(Integer suppyCity) {
		this.suppyCity = suppyCity;
	}

	@Column(name = "suppyAddrLatitude", length = 100)
	public String getSuppyAddrLatitude() {
		return this.suppyAddrLatitude;
	}

	public void setSuppyAddrLatitude(String suppyAddrLatitude) {
		this.suppyAddrLatitude = suppyAddrLatitude;
	}

	@Column(name = "productType")
	public Integer getProductType() {
		return this.productType;
	}

	public void setProductType(Integer productType) {
		this.productType = productType;
	}

	@Column(name = "goodsCity")
	public Integer getGoodsCity() {
		return this.goodsCity;
	}

	public void setGoodsCity(Integer goodsCity) {
		this.goodsCity = goodsCity;
	}

	@Column(name = "goodsAddr", length = 100)
	public String getGoodsAddr() {
		return this.goodsAddr;
	}

	public void setGoodsAddr(String goodsAddr) {
		this.goodsAddr = goodsAddr;
	}

	@Column(name = "goodsAddrLatitude", length = 100)
	public String getGoodsAddrLatitude() {
		return this.goodsAddrLatitude;
	}

	public void setGoodsAddrLatitude(String goodsAddrLatitude) {
		this.goodsAddrLatitude = goodsAddrLatitude;
	}

	@Column(name = "serviceProviderType")
	public Integer getServiceProviderType() {
		return this.serviceProviderType;
	}

	public void setServiceProviderType(Integer serviceProviderType) {
		this.serviceProviderType = serviceProviderType;
	}

	@Column(name = "suppyContact", length = 100)
	public String getSuppyContact() {
		return this.suppyContact;
	}

	public void setSuppyContact(String suppyContact) {
		this.suppyContact = suppyContact;
	}

	@Column(name = "suppyTelephone", length = 100)
	public String getSuppyTelephone() {
		return this.suppyTelephone;
	}

	public void setSuppyTelephone(String suppyTelephone) {
		this.suppyTelephone = suppyTelephone;
	}

	@Column(name = "productDatum", length = 100)
	public String getProductDatum() {
		return this.productDatum;
	}

	public void setProductDatum(String productDatum) {
		this.productDatum = productDatum;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "remarks", length = 500)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createDate", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
