package com.qc.model;

// Generated 2016-10-18 11:21:58 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "qcplus")
public class Product implements java.io.Serializable {

	private int id;
	private Integer orderId;
	private String girard;
	private String name;
	private Double number;
	private Integer orderNo;
	private String remarks;

	public Product() {
	}

	public Product(int id) {
		this.id = id;
	}

	public Product(int id, Integer orderId, String girard, String name,
			Double number, Integer orderNo, String remarks) {
		this.id = id;
		this.orderId = orderId;
		this.girard = girard;
		this.name = name;
		this.number = number;
		this.orderNo = orderNo;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "orderId")
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "girard", length = 40)
	public String getGirard() {
		return this.girard;
	}

	public void setGirard(String girard) {
		this.girard = girard;
	}

	@Column(name = "name", length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "number", precision = 22, scale = 0)
	public Double getNumber() {
		return this.number;
	}

	public void setNumber(Double number) {
		this.number = number;
	}

	@Column(name = "orderNo")
	public Integer getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(Integer orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "remarks", length = 100)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
