package com.qc.model;

// Generated 2016-10-18 11:21:58 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reportinfo generated by hbm2java
 */
@Entity
@Table(name = "reportinfo", catalog = "qcplus")
public class Reportinfo implements java.io.Serializable {

	private int id;
	private Integer orderId;
	private Integer userId;
	private String content;
	private Date descDate;

	public Reportinfo() {
	}

	public Reportinfo(int id) {
		this.id = id;
	}

	public Reportinfo(int id, Integer orderId, Integer userId, String content,
			Date descDate) {
		this.id = id;
		this.orderId = orderId;
		this.userId = userId;
		this.content = content;
		this.descDate = descDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "orderId")
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "userId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "content", length = 200)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "descDate", length = 10)
	public Date getDescDate() {
		return this.descDate;
	}

	public void setDescDate(Date descDate) {
		this.descDate = descDate;
	}

}
