package com.qc.model;

// Generated 2016-10-10 18:19:05 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoleId generated by hbm2java
 */
@Embeddable
public class RoleId implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer isdelete;

	public RoleId() {
	}

	public RoleId(Integer id, String name, Integer isdelete) {
		this.id = id;
		this.name = name;
		this.isdelete = isdelete;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "isdelete")
	public Integer getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleId))
			return false;
		RoleId castOther = (RoleId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getIsdelete() == castOther.getIsdelete()) || (this
						.getIsdelete() != null
						&& castOther.getIsdelete() != null && this
						.getIsdelete().equals(castOther.getIsdelete())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getIsdelete() == null ? 0 : this.getIsdelete().hashCode());
		return result;
	}

}
