package com.qc.model;

// Generated 2016-10-18 11:21:58 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * School generated by hbm2java
 */
@Entity
@Table(name = "school", catalog = "qcplus")
public class School implements java.io.Serializable {

	private SchoolId id;

	public School() {
	}

	public School(SchoolId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "name", column = @Column(name = "name", length = 20)),
			@AttributeOverride(name = "content", column = @Column(name = "content", length = 400)),
			@AttributeOverride(name = "createDate", column = @Column(name = "createDate", nullable = false, length = 19)),
			@AttributeOverride(name = "type", column = @Column(name = "type")) })
	public SchoolId getId() {
		return this.id;
	}

	public void setId(SchoolId id) {
		this.id = id;
	}

}
