package com.qc.model;

// Generated 2016-10-18 11:21:58 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Formula;

/**
 * Scorechange generated by hbm2java
 */
@Entity
@Table(name = "scorechange", catalog = "qcplus")
public class Scorechange implements java.io.Serializable {

	private Integer id;
	private int userid;
	private Integer content;
	private Integer value;
	private Date changeDate;
	private String remark;//备注
	@Column(name="remark")
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	private String username;
	private String contentname;

	@Formula("(select u.loginname from user_login u where u.id = userid)")
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}
	@Formula("(select c.name from configuration c where c.catalog='score' and c.code = content)")
	public String getContentname() {
		return contentname;
	}

	public void setContentname(String contentname) {
		this.contentname = contentname;
	}

	public Scorechange() {
	}

	public Scorechange(int userid) {
		this.userid = userid;
	}

	public Scorechange(int userid, Integer content, Integer value,
			Date changeDate,String remark) {
		this.userid = userid;
		this.content = content;
		this.value = value;
		this.remark=remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "content", nullable = false)
	public Integer getContent() {
		return this.content;
	}

	public void setContent(Integer content) {
		this.content = content;
	}

	@Column(name = "value", nullable = false)
	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "changeDate", length = 10, nullable = false)
	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

}
