package com.qc.model;

// Generated 2016-10-18 11:21:58 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Sendorder generated by hbm2java
 */
@Entity
@Table(name = "sendorder", catalog = "qcplus")
public class Sendorder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -579289891116840369L;
	private Integer id;
	private UserLogin userLogin;
	private String name;
	private String nikename;
	private Integer nature;
	private String email;
	private String telephone;
	private String contact;
	private Integer city;
	private String address;
	private String addrlatitude;
	private String cardphoto;
	private Date createDate;

	public Sendorder() {
	}

	public Sendorder(UserLogin userLogin, String name) {
		this.userLogin = userLogin;
		this.name = name;
	}

	public Sendorder(UserLogin userLogin, String name, String nikename,
			Integer nature, String email, String telephone, String contact,
			Integer city, String address, String addrlatitude,
			String cardphoto, Date createDate) {
		this.userLogin = userLogin;
		this.name = name;
		this.nikename = nikename;
		this.nature = nature;
		this.email = email;
		this.telephone = telephone;
		this.contact = contact;
		this.city = city;
		this.address = address;
		this.addrlatitude = addrlatitude;
		this.cardphoto = cardphoto;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public UserLogin getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(UserLogin userLogin) {
		this.userLogin = userLogin;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "nikename", length = 50)
	public String getNikename() {
		return this.nikename;
	}

	public void setNikename(String nikename) {
		this.nikename = nikename;
	}

	@Column(name = "nature")
	public Integer getNature() {
		return this.nature;
	}

	public void setNature(Integer nature) {
		this.nature = nature;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telephone", length = 50)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "contact", length = 50)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "city")
	public Integer getCity() {
		return this.city;
	}

	public void setCity(Integer city) {
		this.city = city;
	}

	@Column(name = "address", length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "addrlatitude", length = 50)
	public String getAddrlatitude() {
		return this.addrlatitude;
	}

	public void setAddrlatitude(String addrlatitude) {
		this.addrlatitude = addrlatitude;
	}

	@Column(name = "cardphoto", length = 50)
	public String getCardphoto() {
		return this.cardphoto;
	}

	public void setCardphoto(String cardphoto) {
		this.cardphoto = cardphoto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createDate", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
