package com.qc.model;

// Generated 2016-10-18 11:21:58 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UserLogin generated by hbm2java
 */
@Entity
@Table(name = "user_login", catalog = "qcplus", uniqueConstraints = @UniqueConstraint(columnNames = "loginname"))
public class UserLogin implements java.io.Serializable {

	private Integer id;
	private Role role;
	private String loginname;
	private String password;
	private Integer logtype;
	private String qq;
	private String weixin;
	private String inInfo;
	private String facebook;
	private String twitter;
	private String skype;
	private Integer score;
	private Integer money;
	private Integer invitationId;
	private Integer status;
	private Date createDate;
	private Set<Sendorder> sendorders = new HashSet<Sendorder>(0);
	private Set<Receiveorder> receiveorders = new HashSet<Receiveorder>(0);
	private Set<Receiveordercompany> receiveordercompanies = new HashSet<Receiveordercompany>(
			0);

	public UserLogin() {
	}

	public UserLogin(String loginname) {
		this.loginname = loginname;
	}

	public UserLogin(Role role, String loginname, String password,
			Integer logtype, String qq, String weixin, String inInfo,
			String facebook, String twitter, String skype, Integer score,
			Integer money, Integer invitationId, Integer status,
			Date createDate, Set<Sendorder> sendorders,
			Set<Receiveorder> receiveorders,
			Set<Receiveordercompany> receiveordercompanies) {
		this.role = role;
		this.loginname = loginname;
		this.password = password;
		this.logtype = logtype;
		this.qq = qq;
		this.weixin = weixin;
		this.inInfo = inInfo;
		this.facebook = facebook;
		this.twitter = twitter;
		this.skype = skype;
		this.score = score;
		this.money = money;
		this.invitationId = invitationId;
		this.status = status;
		this.createDate = createDate;
		this.sendorders = sendorders;
		this.receiveorders = receiveorders;
		this.receiveordercompanies = receiveordercompanies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roleid")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "loginname", unique = true, nullable = false, length = 20)
	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	@Column(name = "password", length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "logtype")
	public Integer getLogtype() {
		return this.logtype;
	}

	public void setLogtype(Integer logtype) {
		this.logtype = logtype;
	}

	@Column(name = "qq", length = 32)
	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	@Column(name = "weixin", length = 32)
	public String getWeixin() {
		return this.weixin;
	}

	public void setWeixin(String weixin) {
		this.weixin = weixin;
	}

	@Column(name = "inInfo", length = 32)
	public String getInInfo() {
		return this.inInfo;
	}

	public void setInInfo(String inInfo) {
		this.inInfo = inInfo;
	}

	@Column(name = "facebook", length = 32)
	public String getFacebook() {
		return this.facebook;
	}

	public void setFacebook(String facebook) {
		this.facebook = facebook;
	}

	@Column(name = "twitter", length = 32)
	public String getTwitter() {
		return this.twitter;
	}

	public void setTwitter(String twitter) {
		this.twitter = twitter;
	}

	@Column(name = "skype", length = 32)
	public String getSkype() {
		return this.skype;
	}

	public void setSkype(String skype) {
		this.skype = skype;
	}

	@Column(name = "score")
	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	@Column(name = "money")
	public Integer getMoney() {
		return this.money;
	}

	public void setMoney(Integer money) {
		this.money = money;
	}

	@Column(name = "invitationId")
	public Integer getInvitationId() {
		return this.invitationId;
	}

	public void setInvitationId(Integer invitationId) {
		this.invitationId = invitationId;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createDate", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userLogin")
	public Set<Sendorder> getSendorders() {
		return this.sendorders;
	}

	public void setSendorders(Set<Sendorder> sendorders) {
		this.sendorders = sendorders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userLogin")
	public Set<Receiveorder> getReceiveorders() {
		return this.receiveorders;
	}

	public void setReceiveorders(Set<Receiveorder> receiveorders) {
		this.receiveorders = receiveorders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userLogin")
	public Set<Receiveordercompany> getReceiveordercompanies() {
		return this.receiveordercompanies;
	}

	public void setReceiveordercompanies(
			Set<Receiveordercompany> receiveordercompanies) {
		this.receiveordercompanies = receiveordercompanies;
	}

}
